// <auto-generated />
namespace Back_End_BD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IEVN1001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IEVN1001));
        
        string IMigrationMetadata.Id
        {
            get { return "202211112337068_IEVN1001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
